version: "3"

services:
  maplab:
    image: maplab
    build:
      context: ./docker_ctx
      dockerfile: ../Dockerfile
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/maps:/tmp/maps
    network_mode: host
